// <auto-generated />
namespace Test.Model.Migration.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TypeRiskM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TypeRiskM));
        
        string IMigrationMetadata.Id
        {
            get { return "202007290300444_TypeRiskM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
