//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyClientM
    {
        public int IdPolicyClient { get; set; }
        public int IdClient { get; set; }
        public int IdPolicy { get; set; }
        public int CoveragePercentage { get; set; }
        public bool Active { get; set; }
        public string UserCreate { get; set; }
        public System.DateTime DateCreate { get; set; }
    }
}
